[project]
name = "document-master-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "python-pptx>=1.0.2",
    "ruff>=0.14.5",
    "uvicorn>=0.38.0",
]
